plugins:
  - "@semantic-release/commit-analyzer"
  - - "semantic-release-helm"
    - chartPath: './'
      onlyUpdateVersion: true
  - - "@semantic-release/git"
    - assets:
      - Chart.yaml
      message': "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
branches:
  - "main"
  - "fix-helm-release-ci"
  - "v([0-9]\\.*)*(?<!\\.)$"