name: CI

on:
  # push:
  # branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - v*

jobs:
  semantic-release-test:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    # needs: build-operator
    env:
      IMG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
     
      - name: Login to Github container repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.1
            semantic-release-helm@2.2.0 

      - name: Install helm
        uses: azure/setup-helm@v4

      - name: Update helm chart
        run: |
          git checkout main
          sed -Ei \
           -e 's/^(version\:) .*/\1 '${{ env.VERSION }}'/g' \
           -e 's/^(appVersion\:) .*/\1 "'${{ env.VERSION }}'"/g' \
           charts/dragonfly-operator/Chart.yaml          
          
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"          

          git commit \
          -m 'chore(helm-chart): update to ${{ env.VERSION }}' \
          charts/dragonfly-operator/Chart.yaml

          git push

  build-operator:
    runs-on: ubuntu-latest
    env:
      IMG: ghcr.io/${{ github.repository }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Docker Build
        run: |
          make docker-build

      - uses: helm/kind-action@v1.7.0
        with:
          cluster_name: kind
          config: ./hack/kind-config.yaml
      - name: Run tests
        timeout-minutes: 12
        run: |
          make docker-kind-load
          make deploy
          make test

      - name: Cleanup
        run: |
          make undeploy

  release-operator:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    # needs: build-operator
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    env:
      IMG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Build
        run: |
          make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github container repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git

      - name: Install helm
        uses: azure/setup-helm@v4

      - name: Update helm chart
        run: |
          git checkout main
          sed -Ei \
           -e 's/^(version\:) .*/\1 '${{ env.VERSION }}'/g' \
           -e 's/^(appVersion\:) .*/\1 "'${{ env.VERSION }}'"/g' \
           charts/dragonfly-operator/Chart.yaml          
          
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"          

          git commit \
          -m 'chore(helm-chart): update to ${{ env.VERSION }}' \
          charts/dragonfly-operator/Chart.yaml

          git push
      - name: Push Helm chart as OCI to Github
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          helm registry login -u ${{ github.actor }} --password-stdin ghcr.io
          
          helm package charts/dragonfly-operator
          
          # Lowercase the repository name when running this job in forked repos
          REPOSITORY=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')

          helm push dragonfly-operator-${{ env.VERSION }}.tgz oci://ghcr.io/$REPOSITORY/helm

      - name: Build and Publish image into GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          platforms: |
            linux/amd64
            linux/arm64
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: publish github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/dragonfly-operator
            LICENSE
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}

            Docker image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          draft: true
